id: PE9DF1629
initial_creation_type: ocr
source_metadata:
  volumes:
    ba344d6b76b1409392c88fc828902e1d:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: དབུ་མ་འཁྲུལ་པ་འཇོམས་པ།
      total_pages: 1605
      volume_number: 57
